apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: service-mysql
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql/
          - name: telegraf-config
            subPath: telegraf.conf
            mountPath: /etc/telegraf/telegraf.conf
            readOnly: true
          envFrom:
            - secretRef:
                name: telegraf-secret
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: telegraf-config
          configMap:
            name: telegraf-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
      - ReadWriteOnce
  resources:
      requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql # 이 name이 wp-config.php에서 DB_HOST 가 된다.!!
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql
    targetPort: 3306
